export const RACONS = [
    {
        slug: 'viatges',
        nom: 'Viajes',
        emoji: '🗺️',
        descripcio: 'Regiones, pueblos y lugares de interés visitados',
        actiu: true,
        ruta: '/viatges',
        color: '#4f6d7a',
        gradient: 'linear-gradient(135deg, #4f6d7a 0%, #6b8f9e 100%)',
    },
    {
        slug: 'cuina',
        nom: 'Cocina',
        emoji: '🍳',
        descripcio: 'Recetas, tradiciones culinarias y secretos de la cocina',
        actiu: false,
        ruta: '/cuina',
        color: '#c1666b',
        gradient: 'linear-gradient(135deg, #c1666b 0%, #d4888c 100%)',
    },
    {
        slug: 'plantes',
        nom: 'Plantas',
        emoji: '🌿',
        descripcio: 'Cría, hibridación y curas de plantas',
        actiu: true,
        ruta: '/plantes',
        color: '#48734c',
        gradient: 'linear-gradient(135deg, #48734c 0%, #6a9b6e 100%)',
    },
    {
        slug: 'bricolatge',
        nom: 'Bricolaje',
        emoji: '🔧',
        descripcio: 'Proyectos de bricolaje, construcción y reparación',
        actiu: false,
        ruta: '/bricolatge',
        color: '#8b6f47',
        gradient: 'linear-gradient(135deg, #8b6f47 0%, #a8895e 100%)',
    },
];
